// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BlazorApp1.Models;

public partial class Emptbl
{
    public int Id { get; set; }

    public string Name { get; set; }


    public int Age { get; set; }

    public string Address { get; set; }

    public bool Isactive { get; set; }

    public string Skills { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Skill> SkillsNavigation { get; set; } = new List<Skill>();
}