// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlazorApp1.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BlazorApp1.Models
{
    public partial interface IEmpdbContextProcedures
    {
        Task<List<SP_selectResult>> SP_selectAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
