// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorApp1.Models
{
    public partial class sp_skillsResult
    {
        public int skill_id { get; set; }
        public string name { get; set; }
    }
}
